name: financas
version: '1.0.0'
config-version: 2

profile: financas

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  financas:
    staging:
      +materialized: view
      +schema: stg
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  financas:
    +schema: raw